# These are supported funding model platforms

github: # Diego Emanuel
patreon: https://www.patreon.com/user?u=78372783&fan_landing=true&view_as=public
open_collective: # Diego Emanuel
ko_fi: # Diego Emanuel
tidelift: # Diego Emanuel
community_bridge: # Diego Emanuel
liberapay: #Diego Emanuel
issuehunt: # Diego Emanuel
otechie: # Diego Emanuel
lfx_crowdfunding: # Diego Emanuel
custom: # Diego Emanuel fc
up
