name: Daily Development Analysis

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    paths:
      - 'README.md'

jobs:
  analyze-development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar depend칡ncias
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      - name: Gerenciar mudan칞as locais
        run: |
          git add .
          git commit -m "Salvando mudan칞as locais antes do pull [skip ci]" || echo "Nada para commit"

      - name: Atualizar branch local
        run: git pull --rebase origin main

      - name: Executar an치lise de desenvolvimento
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/analysis.py

      - name: Commit das mudan칞as no README
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "游늵 Atualiza칞칚o autom치tica do README com an치lise di치ria [skip ci]"
          git push
