name: Update README with Recent Commits

on:
  schedule:
    # Executa diariamente às 8:00 AM (UTC)
    - cron: '0 8 * * *'
  push:
    # Executa ao modificar arquivos do repositório
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install gitpython

    - name: Executar script de análise
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python scripts/analysis.py

    - name: Commit e push das alterações
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull.rebase true
        git add README.md
        git commit -m "📊 Atualização automática do README com análise diária [skip ci]" || echo "Nada para atualizar"
        git push
